/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


void
calculadora_1(char *host, int ent1, char op, int ent2)
{
	CLIENT *clnt;
	double  *result;
	int entero1 = ent1, entero2 = ent2;
	char operacion = op;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, CALCVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	printf("\nRealizando la operacion %i %c %i \n",entero1,operacion,entero2);

	switch(operacion){
		case '+':
			result = sumar_1(entero1,entero2,clnt);
			printf("\nEl resultado de la suma ha sido: %f",*result);
			break;
		case '-':
			result = restar_1(entero1,entero2,clnt);
			printf("\nEl resultado de la resta ha sido: %f",*result);
			break;
		case '*':
			result = multiplicar_1(entero1,entero2,clnt);
			printf("\nEl resultado de la multiplicacion ha sido: %f",*result);
			break;
		case 'x':
			result = multiplicar_1(entero1,entero2,clnt);
			printf("\nEl resultado de la multiplicacion ha sido: %f",*result);
			break;
		case '/':
			result = dividir_1(entero1,entero2,clnt);
			printf("\nEl resultado de la division ha sido: %f",*result);
			break;
	}

	if(result == NULL){
		clnt_perror(clnt,"RESULTADO INVALIDO");
	}


#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

int
main (int argc, char *argv[])
{
	if(argc < 5){
		printf("Error: Falta de datos desde la erminal, la cadena de datos de entrada tiene que ser -> <host> <entero> <operacion> <entero> \n");
		exit(1);
	}
	
	char *host = argv[1];
	int entero1 = atoi(argv[2]), entero2 = atoi(argv[4]);
	char operacion = (char)argv[3][0];

	calculadora_1(host,entero1,operacion,entero2);
	exit(0);
}
