/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"

bool_t
xdr_t_vector (XDR *xdrs, t_vector *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->t_vector_val, (u_int *) &objp->t_vector_len, ~0,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sumar_1_argument (XDR *xdrs, sumar_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_restar_1_argument (XDR *xdrs, restar_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_multiplicar_1_argument (XDR *xdrs, multiplicar_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_dividir_1_argument (XDR *xdrs, dividir_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sumavectores_1_argument (XDR *xdrs, sumavectores_1_argument *objp)
{
	 if (!xdr_t_vector (xdrs, &objp->vec1))
		 return FALSE;
	 if (!xdr_t_vector (xdrs, &objp->vec2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_restavectores_1_argument (XDR *xdrs, restavectores_1_argument *objp)
{
	 if (!xdr_t_vector (xdrs, &objp->vec1))
		 return FALSE;
	 if (!xdr_t_vector (xdrs, &objp->vec2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_productovectores_1_argument (XDR *xdrs, productovectores_1_argument *objp)
{
	 if (!xdr_t_vector (xdrs, &objp->vec1))
		 return FALSE;
	 if (!xdr_t_vector (xdrs, &objp->vec2))
		 return FALSE;
	return TRUE;
}
